name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 18

            - run: npm i -g npm@9 --registry=https://registry.npmjs.org
            - run: npm ci
            - run: npm test
            - run: npm run build

            - uses: codecov/codecov-action@v3
              with:
                  files: ./coverage/lcov.info
                  fail_ci_if_error: true
                  verbose: true
