name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 20

            - run: npm i -g npm@10 --registry=https://registry.npmjs.org
            - run: npm ci
            - run: npm run ci

            - uses: codecov/codecov-action@v3
              with:
                  files: ./lcov.info
                  fail_ci_if_error: false
                  verbose: true
