name: Node.js CI

on: [push]

jobs:
  build:
    name: Node ${{ matrix.node }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14', '15', '16', '17']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: |
          npm ci
          npm test
          npm run build

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
